services:
  portfolio:
    container_name: portfolio
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`afbolivarg.com`) || Host(`www.afbolivarg.com`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio.middlewares=redirect-to-non-www"
      - "traefik.http.middlewares.portfolio-redirect-to-non-www.redirectregex.regex=^https?://www.afbolivarg.com/(.*)"
      - "traefik.http.middlewares.portfolio-redirect-to-non-www.redirectregex.replacement=https://afbolivarg.com/$${1}"
      - "traefik.http.middlewares.portfolio-redirect-to-non-www.redirectregex.permanent=true"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true