services:
  portfolio:
    container_name: portfolio
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`afbolivarg.com`)"
      - "traefik.http.services.potfolio.loadbalancer.server.port=3000"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true